---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.nginx-static-deployment }}
  namespace: {{ .values.namespace }}
  labels:
    name: {{ .values.labels }}
#  annotations:
#    flux.weave.works/tag.podinfo: glob:*
#    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ .values.labels }}
  template:
    metadata:
      labels:
        name: {{ .values.labels }}
    spec:
      # automountServiceAccountToken: false
      containers:
      - name: {{ .values.container-name }}
        image: {{ .values.imagename }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
